# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)'
    outputType: 'Process'
    orchestratorConnection: 'UiPathMyOrgDefaultTenant'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)\Output'
    ArtifactName: 'LOlivierDU'
    publishLocation: 'Container'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: ''
    ArtifactName: 'assetFile'
    publishLocation: 'Container'